### ISSUE TITLE
OpenAPI FormUrlEncodedContent

### ISSUE THREAD

**Issue by scottsanpedro** [christianhelle/apiclientcodegen#585] opened 2023-07-13 11:42 UTC
Hi. I am getting 500 errors after the latest update.
It seems that payload type has changed from json to FormUrlEncodedContent.
Example.

```
if (x_Version != null)
                        request_.Headers.TryAddWithoutValidation("X-Version", ConvertToString(x_Version, System.Globalization.CultureInfo.InvariantCulture));

                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(entity, _settings.Value);

                    var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);

                    var content_ = new System.Net.Http.FormUrlEncodedContent(dictionary_);

                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");`
```

From

```
if (x_Version != null)
                        request_.Headers.TryAddWithoutValidation("X-Version", ConvertToString(x_Version, System.Globalization.CultureInfo.InvariantCulture));
                    var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(entity, _settings.Value));
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
```

This is version 2022, latest.

From ChatGPT.
It seems like the generated OpenAPI code is not correctly passing the payload when calling the API endpoint. In the generated code, it's using a FormUrlEncodedContent to serialize the entity, but the content type is set to "application/json", which is incorrect.

To Reproduce

Generate client code for a swagger.json using OpenApi Generator

Visual Studio Extension (please complete the following information):

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.5
Extension Version: 1.7.1.7

Thanks Scott

**Comment by christianhelle** [comment] 2023-07-13 12:15
@scottsanpedro thanks for taking the time to report this. I'm currently on my summer vacation but I'll try to find the time to take a look at this, if the problem is trivial, then I'll fix it immediately, otherwise, I'll take a deeper look at this and fix whatever is wrong in 2 weeks

**Comment by christianhelle** [comment] 2023-07-13 12:17
@scottsanpedro Would you mind sharing the OpenAPI specifications file that fails? It would make troubleshooting this much easier for me

**Comment by scottsanpedro** [comment] 2023-07-13 12:42
[SwaggerFile.txt](https://github.com/christianhelle/apiclientcodegen/files/12039440/SwaggerFile.txt)

Hi Christian. File attached. Really sorry to disturb you. No panic on this.
I'm not the most knowledgeable on these so hoping not a wild goose chase.
I ran it through NSwagStudio and am getting the same outcome. Using C#Client

` if (x_Version != null)
                        request_.Headers.TryAddWithoutValidation("X-Version", ConvertToString(x_Version, System.Globalization.CultureInfo.InvariantCulture));
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(entity, _settings.Value);
                    var dictionary_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json_, _settings.Value);
                    var content_ = new System.Net.Http.FormUrlEncodedContent(dictionary_);`

The code retrieves data fine i.e. GET but POSTS all fail across all my API now.
Much Appreciated.

**Comment by scottsanpedro** [comment] 2023-07-13 15:59
Found this.
[https://github.com/RicoSuter/NSwag/issues/3414](url)

**Comment by scottsanpedro** [comment] 2023-07-13 17:10
So it appears to be a bug in NSwag.
Now looking for your latest version using 
Generated using the NSwag toolchain v13.8.2.0 (NJsonSchema v10.2.1.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org).
Imagine this can be closed now.
Have a good holiday. Appreciate your help.

**Comment by scottsanpedro** [comment] 2023-07-13 17:41
Fix for anyone else that gets this. 
[https://github.com/RicoSuter/NSwag/issues/3414#issuecomment-826479920](url)

Hi, hopefully this helps someone who has this issue on Asp.net (.NET Framework)

I added the following custom filter class:

    internal class AssignContentTypeFilter : IOperationFilter
    {
        public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription)
        {
            operation.consumes.Clear();
            operation.consumes.Add("application/json");

            operation.produces.Clear();
            operation.produces.Add("application/json");
        }
    }
then in SwaggerConfig.cs:

c.OperationFilter<AssignContentTypeFilter>();

reference link: https://stackoverflow.com/questions/58973329/asp-net-core-3-0-swashbuckle-restrict-responses-content-types-globally

**Comment by christianhelle** [comment] 2023-07-28 11:08
Thanks for looking into this in detail @scottsanpedro and for sharing a work around.

I will close this issue

**Closed by christianhelle** 2023-07-28 11:08 UTC
Labels: bug
